name: KernelSU Workflow

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Enter the kernel version'
        default: 'default_kernel_version'
        required: false
      boot_file_url:
        description: 'URL to download the boot file'
        default: 'default_boot_file_url'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 1: Download the boot file
    - name: Download Boot File
      uses: actions/download-artifact@v3
      with:
        url: ${{ github.event.inputs.boot_file_url }}
        name: boot

    # Step 2: Download MagiskBoot
    - name: Download MagiskBoot
      run: |
        wget https://github.com/topjohnwu/Magisk/releases/download/v24.3/Magisk-v24.3.zip
        unzip Magisk-v24.3.zip -d Magisk
        mv Magisk/magiskboot .

    # Step 3: Download the patched ko file
    - name: Get KernelSU Action Run ID
      id: get_kernelsu_run_id
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/tiann/KernelSU/actions/workflows/build-lkm.yml/runs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download KernelSU ko File
      uses: actions/download-artifact@v3
      with:
        workflow_run_id: ${{ fromJson(steps.get_kernelsu_run_id.outputs.data).workflow_runs[0].id }}
        name: ${{ github.event.inputs.kernel_version }}_kernelsu.ko

    # Step 4: Download ksud and manager
    - name: Get Manager Action Run ID
      id: get_manager_run_id
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/tiann/KernelSU/actions/workflows/build-manager.yml/runs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download ksud and manager
      uses: actions/download-artifact@v3
      with:
        workflow_run_id: ${{ fromJson(steps.get_manager_run_id.outputs.data).workflow_runs[0].id }}
        name: ksud-x86_64-linux-android,manager
