name: Custom Workflow

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel Version'
        default: 'android12-5.10'
        required: true
      boot_url:
        description: 'URL to download the boot file'
        default: 'http://liaoke.link:5244/d/onedrive/boot.img'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set kernel version input
      id: kernel_version
      run: echo "::set-output name=version::${{ github.event.inputs.kernel_version }}"

    - name: Download boot file
      run: wget -P . ${{ github.event.inputs.boot_url }}

    - name: Download magiskboot
      run: wget -P . https://github.com/magojohnji/magiskboot-linux/blob/main/x86_64/magiskboot

    - name: Get latest KernelSU build LKM workflow run ID
      id: get_kernelsu_lkm_run_id
      run: |
        curl -s "https://api.github.com/repos/tiann/KernelSU/actions/workflows/build-lkm.yml/runs" | \
        jq -r '.workflow_runs | sort_by(.run_number) | last|.id'

    - name: Set KERNELSU_BUILD_ID environment variable
      run: echo "KERNELSU_BUILD_ID=${{ steps.get_kernelsu_lkm_run_id.outputs.result }}" >>$GITHUB_ENV

    - name: Download KernelSU ko file
      uses: actions/download-artifact@v3
      with:
        workflow_run_id: ${{ env.KERNELSU_BUILD_ID }}
        name: ${{ steps.kernel_version.outputs.version }}_kernelsu.ko
        path: .

    - name: Get latest KernelSU build manager workflow run ID
      id: get_kernelsu_manager_run_id
      run: |
        curl -s "https://api.github.com/repos/tiann/KernelSU/actions/workflows/build-manager.yml/runs" | \
        jq -r '.workflow_runs | sort_by(.run_number) | last|.id'

    - name: Set KERNELSU_MANAGER_BUILD_ID environment variable
      run: echo "KERNELSU_MANAGER_BUILD_ID=${{ steps.get_kernelsu_manager_run_id.outputs.result }}" >>$GITHUB_ENV

    - name: Download ksud and manager files
      uses: actions/download-artifact@v3
      with:
        workflow_run_id: ${{ env.KERNELSU_MANAGER_BUILD_ID }}
        name: |
          ksud-x86_64-linux-android
          manager
        path: .
