name: Patch boot

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel Version'
        default: 'android12-5.10'
        required: true

jobs:
  build:
    runs-on: actuated-aarch64
    steps:
    - name: Download magiskboot
      id: download_magiskboot
      run: wget -P . https://github.com/magojohnji/magiskboot-linux/blob/main/x86_64/magiskboot

    - name: Download KernelSU ko file
      id: download_kernelsu_ko
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-lkm.yml
        workflow_conclusion: success
        name: ${{ inputs.kernel_version }}-lkm
        path: .

    - name: ksud
      id: download_ksud
      run: wget https://github.com/liaoke01/patch-kernelsu-for-boot/blob/main/ksud
      
    - name: Download boot files
      id: download_boot_files
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: liaoke01/BootIMGExtractAction
        branch: main
        workflow: BootIMGExtractAction.yml
        workflow_conclusion: success
        name: boot.img
        path: .
      

    - name: Download manager files
      id: download_manager_files
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-manager.yml
        workflow_conclusion: success
        name: manager
        path: .

    - name: ls
      id: list_files
      run: |
        ls
        arch
        ldd ksud

    - name: Set execute permissions
      id: set_permissions
      run: |
        chmod +x ksud

    - name: patch boot
      id: patch_boot
      run: ./ksud boot-patch -b boot.img -m kernelsu.ko
