name: Patch boot

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 1

    - name: Download magiskboot
      run: |
       wget https://github.com/xiaoxindada/magiskboot_ndk_on_linux/releases/latest/download/magiskboot.7z
       sudo apt update
       sudo apt install p7zip p7zip-full p7zip-rar
       7z x magiskboot.7z out/arm64-v8/magiskboot
       
    - name: Download KernelSU ko file
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-lkm.yml
        workflow_conclusion: success
        name: android12-5.10_kernelsu.ko
        path: .
      
    - name: Download boot files
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: liaoke01/BootIMGExtractAction
        branch: main
        workflow: BootIMGExtractAction.yml
        workflow_conclusion: success
        name: boot.img
        path: .
        
    - name: Download ksud files
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: liaoke01/KernelsuSU
        branch: kmod
        workflow: build-ksud.yml
        workflow_conclusion: success
        name: ksud-aarch64-unknown-linux-gnu 
        path: .
     
    - name: Download manager files
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-manager.yml
        workflow_conclusion: success
        name: manager
        path: .

    - name: Set execute permissions and rename
      run: |
        ls
        chmod +x ksud
        chmod +x magiskboot
        mv android12-5.10_kernelsu.ko kernelsu.ko
        mv /aarch64-unknown-linux-gnu/release/ksud .
        
    - name: patch boot
      run: |
        file ksud
        file magiskboot
        file boot.img
        file kernelsu.ko
        ./ksud boot-patch -b boot.img -m kernelsu.ko --magiskboot magiskboot
