name: Patch boot

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel Version'
        default: 'android12-5.10'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
     matrix: 
      arch: [arm64]
    steps:
    - name: Download magiskboot
      run: wget -P . https://github.com/magojohnji/magiskboot-linux/blob/main/x86_64/magiskboot

    - name: Download KernelSU ko file
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-lkm.yml
        workflow_conclusion: success
        name: ${{ inputs.kernel_version }}-lkm
        path: .

    - name: ksud
      run: wget https://github.com/liaoke01/patch-kernelsu-for-boot/blob/main/ksud
      
    - name: Download boot files
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: liaoke01/BootIMGExtractAction
        branch: main
        workflow: BootIMGExtractAction.yml
        workflow_conclusion: success
        name: boot.img
        path: .
        
    - name: Download manager files
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-manager.yml
        workflow_conclusion: success
        name: manager
        path: .
        
    - name: ls
      run: |
        ls
        pwd

    - name: Set execute permissions
      run: |
        chmod +x ksud
        chmod +x magiskboot
        
    - name: patch boot
      run: ./ksud boot-patch -b boot.img -m kernelsu.ko
