name: Custom Workflow

on:
  push:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel Version'
        default: 'android12-5.10'
        required: true
      boot_url:
        description: 'URL to download the boot file'
        default: 'http://liaoke.link:5244/d/onedrive/boot.img'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set kernel version input
      id: kernel_version
      run: echo "::set-output name=version::${{ github.event.inputs.kernel_version }}"

    - name: Download boot file
      run: wget -P . ${{ github.event.inputs.boot_url }}

    - name: Download magiskboot
      run: wget -P . https://github.com/magojohnji/magiskboot-linux/blob/main/x86_64/magiskboot

    - name: Download KernelSU ko file
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-lkm.yml
        workflow_conclusion: success
        name: ${{ steps.kernel_version.outputs.version }}_kernelsu.ko
        path: .

    - name: Download ksud files
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-manager.yml
        workflow_conclusion: success
        name: ksud-x86_64-linux-android
        path: .
    - name: Download manager files
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-manager.yml
        workflow_conclusion: success
        name: manager
        path: .
