name: Custom Workflow

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel Version'
        default: 'android12-5.10'
      boot_file:
        description: 'Boot File URL'
        default: 'http://liaoke.link:5244/d/onedrive/boot.img'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    # Download boot file from user input or default
    - name: Download Boot File
      uses: actions/download-artifact@v2
      with:
        url: ${{ github.event.inputs.boot_file }}
        path: .

    # Download magiskboot
    - name: Download Magiskboot
      run: wget -O magiskboot https://github.com/magojohnji/magiskboot-linux/blob/main/x86_64/magiskboot

    # Download KernelSU ko file
    - name: Get KernelSU ko File
      id: get_ksu_artifact
      uses: actions/github-script@v6
      with:
        script: |
          const response = await github.request('GET /repos/tiann/KernelSU/actions/workflows/build-lkm.yml/runs?branch=main&event=push')
          const latestRun = response.data.workflow_runs[0]
          const artifactResponse = await github.request(`GET /repos/tiann/KernelSU/actions/runs/${latestRun.id}/artifacts?per_page=100`)
          const artifact = artifactResponse.data.artifacts.find(a => a.name === `${context.payload.inputs.kernel_version}_kernelsu.ko`)
          return {
            artifact_id: artifact.id,
            run_id: latestRun.id
          }

    - name: Download KernelSU ko Artifact
      uses: actions/download-artifact@v2
      with:
        workflow_run_id: ${{ steps.get_ksu_artifact.outputs.run_id }}
        artifact_name: ${{ github.event.inputs.kernel_version }}_kernelsu.ko
        path: .

    # Download ksud and manager files
    - name: Get ksud and manager Artifacts
      id: get_ksud_manager_artifact
      uses: actions/github-script@v6
      with:
        script: |
          const response = await github.request('GET /repos/tiann/KernelSU/actions/workflows/build-manager.yml/runs?branch=main&event=push')
          const latestRun = response.data.workflow_runs[0]
          return {
            run_id: latestRun.id
          }

    - name: Download ksud Artifact
      uses: actions/download-artifact@v2
      with:
        workflow_run_id: ${{ steps.get_ksud_manager_artifact.outputs.run_id }}
        artifact_name: ksud-x86_64-linux-android
        path: .

    - name: Download manager Artifact
      uses: actions/download-artifact@v2
      with:
        workflow_run_id: ${{ steps.get_ksud_manager_artifact.outputs.run_id }}
        artifact_name: manager
        path: .
