name: Patch boot

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel Version'
        default: 'android12-5.10'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download boot file
      run: wget -P . https://223-111-154-147.pd1.123pan.cn:30443/download-cdn.123pan.cn/123-268/f6684999/1812118708-0/f66849994544038fcb75fd71de147d0c/c-m26?v=5&t=1710471911&s=1710471911f775a329361b7234fb7342741907cf46&r=GP6FH4&bzc=1&bzs=1812077907&filename=boot.img&x-mf-biz-cid=28e90817-52a9-48ee-831d-4fd4e8c1cf49-47df1e&auto_redirect=0&ndcp=1&cache_type=1&xmfcid=4f19600d-e896-4174-be5a-bbaa3ea7e1c8-1-50111d3b1

    - name: Download magiskboot
      run: wget -P . https://github.com/magojohnji/magiskboot-linux/blob/main/x86_64/magiskboot

    - name: Download KernelSU ko file
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-lkm.yml
        workflow_conclusion: success
        name: ${{ inputs.kernel_version }}_kernelsu.ko
        path: .

    - name: dojfk
      run: wget https://223-111-154-148.pd1.123pan.cn:30443/download-cdn.123pan.cn/123-280/c2fd9966/1812077907-0/c2fd99669c0a0c45a582d120914fd518/c-m27?v=5&t=1710480326&s=17104803265ce14ed0e66993c91b02139373f25875&r=GH1F00&bzc=1&bzs=1812077907&filename=ksud&x-mf-biz-cid=39c8b7a9-8f15-4498-ab44-9e524c8f88dd-73d8e5&auto_redirect=0&ndcp=1&cache_type=1&xmfcid=18b12926-1d58-4add-8145-1a2b1ba4912f-1-50111d3b1

    - name: Download manager files
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: tiann/KernelSU
        branch: kmod
        workflow: build-manager.yml
        workflow_conclusion: success
        name: manager
        path: .
        
    - name: ls
      run: |
        ls
        pwd

    - name: Set execute permissions
      run: |
        chmod +x ksud
        chmod +x magiskboot
        
    - name: patch boot
      run: ksud boot-patch -b boot.img -m kernelsu.ko
