name: Custom Workflow

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Enter the kernel version'
        default: 'android12-5.10'
      boot_file_url:
        description: 'Enter the URL to download the boot file'
        default: 'http://liaoke.link:5244/d/onedrive/boot.img'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up kernel version input
      id: kernel_version_input
      run: echo "::set-output name=kernel_version::${{ github.event.inputs.kernel_version }}"

    - name: Set up boot file URL input
      id: boot_file_url_input
      run: echo "::set-output name=boot_file_url::${{ github.event.inputs.boot_file_url }}"

    - name: Download boot file
      run: wget -O boot ${{ steps.boot_file_url_input.outputs.boot_file_url }}

    - name: Download magiskboot
      run: wget -O magiskboot https://github.com/magojohnji/magiskboot-linux/blob/main/x86_64/magiskboot

    - name: Get latest KernelSU build ID
      id: get_kernelsu_build_id
      run: |
        latest_build_url="https://api.github.com/repos/tiann/KernelSU/actions/workflows/build-lkm.yml/runs/latest"
        kernelsu_build_id=$(curl -s -X GET -H "Accept: application/vnd.github.v3+json" "$latest_build_url" | jq -r '.id')
        echo "KERNELSU_BUILD_ID=$kernelsu_build_id" >>$GITHUB_ENV 

    - name: Download KernelSU ko file
      uses: actions/download-artifact@v3
      with:
        workflow_run_id: ${{ $KERNELSU_BUILD_ID }}
        name: ${{ steps.kernel_version_input.outputs.kernel_version }}_kernelsu.ko

    - name: Get latest Manager build ID
      id: get_manager_build_id
      run: |
        echo "::set-output name=manager_build_id::$(curl -s 'https://api.github.com/repos/tiann/KernelSU/actions/workflows/build-manager.yml/runs' | jq -r '.workflow_runs | sort_by(.created_at) | last |)"

    - name: Download ksud and manager files
      uses: actions/download-artifact@v3
      with:
        workflow_run_id: ${{ steps.get_manager_build_id.outputs.manager_build_id }}
        name: |
          ksud-x86_64-linux-android
          manager
