name: KernelSU Workflow
on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Enter the kernel version'
        required: true
        default: android12-5.10
      boot_input:
        description: 'Enter the boot file URL'
        required: true
        default: http://liaoke.link:5244/d/onedrive/boot.img

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set kernel version and patch file name
      run: |
        echo "KERNEL_VERSION=${{ github.event.inputs.kernel_version }}" >>$GITHUB_ENV
        echo "PATCH_FILE=${{ github.event.inputs.kernel_version }}_kernelsu.ko" >>$GITHUB_ENV

    - name: Download boot file
      run: wget ${{ github.event.inputs.boot_input }} -O boot

    - name: Download magiskboot
      run: wget https://github.com/magojohnji/magiskboot-linux/blob/main/x86_64/magiskboot -O magiskboot
      # Replace https://example.com/magiskboot with the actual download link for magiskboot

    - name: Get latest KernelSU build-lkm.yml action run ID
      id: get_kernel_su_run_id
      run: |
        response=$(curl -s https://api.github.com/repos/tiann/KernelSU/actions/workflows/build-lkm.yml/runs)
        latest_run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
        echo "::set-output name=run_id::$latest_run_id"

    - name: Download patch ko file
      run: |
        wget https://github.com/tiann/KernelSU/actions/runs/${{ steps.get_kernel_su_run_id.outputs.run_id }}/artifacts -O$PATCH_FILE

    - name: Get latest KernelSU build-manager.yml action run ID
      id: get_manager_run_id
      run: |
        response=$(curl -s https://api.github.com/repos/tiann/KernelSU/actions/workflows/build-manager.yml/runs)
        latest_run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
        echo "::set-output name=run_id::$latest_run_id"

    - name: Download ksud and manager
      run: |
        wget https://github.com/tiann/KernelSU/actions/runs/${{ steps.get_manager_run_id.outputs.run_id }}/artifacts -O ksud-x86_64-linux-android
        wget https://github.com/tiann/KernelSU/actions/runs/${{ steps.get_manager_run_id.outputs.run_id }}/artifacts -O manager

    # Add more steps as needed for your workflo
